name = "dotfak-contractor-management"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/worker"

[vars]
NEXT_PUBLIC_API_URL = "https://dotfak-contractor-management.onrender.com"
NEXT_PUBLIC_APP_NAME = "DotFak Contractor Management"
