name = "dotfak-contractor-management"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/server-functions/default/worker.mjs"
no_bundle = true

[vars]
NEXT_PUBLIC_API_URL = "https://dotfak-contractor-management.onrender.com"
NEXT_PUBLIC_APP_NAME = "DotFak Contractor Management"
