name = "dotfak-contractor-management"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/worker"

[vars]
NEXT_PUBLIC_API_URL = "http://q0c480kc0gcokkkk8ksggoso.172.190.9.72.sslip.io"
NEXT_PUBLIC_APP_NAME = "DotFak Contractor Management"
